<?php

declare(strict_types=1);

namespace Cresset\Jibs;

// GENERATED by scripts/publish-composer-branch.sh — the jibs binary version
// this Composer package installs. Always matches the package's git tag, so
// `composer require cresset/jibs:0.1.0` fetches the jibs-v0.1.0 binary.
const JIBS_VERSION = '0.1.0';
