<?php

declare(strict_types=1);

namespace Cresset\Jibs;

// GENERATED by scripts/publish-composer-branch.sh — the jibs binary
// version this Composer package installs. Always matches the package's git
// tag.
const JIBS_VERSION = '0.3.0';
